name: Create Release
on: 
    push:
        branches:
            - master
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Get Version
              id: getVersion
              run: |
                VERSION=$(node -p "require('./package.json').version")
                echo "version=v$VERSION" >> $GITHUB_ENV

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with: 
                tag_name: ${{env.version}}
                name: ${{env.version}}
                draft: false
                prerelease: false
                generate_release_notes: true
                

